language: python
dist: xenial
cache: pip
python: "3.6"

jobs:
  include:
    - stage: test
      if: branch != release/docs
      python: "3.6"
      install: pip install -U -r requirements-ci.txt
      script: pytest --cov=./
      after_success: codecov

    - stage: test
      if: branch != release/docs
      python: "3.7"
      install: pip install -U -r requirements-ci.txt
      script: pytest

    - stage: build and deploy docs
      if: branch = release/docs
      before_install:
        - nvm install 8
        - nvm use 8
      install:
        - pip install -U -r requirements-ci.txt
        - npm install --only=dev
      script:
        - pydocmd generate
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        repo: bocadilloproject/bocadilloproject.github.io
        github-token: $GITHUB_TOKEN
        target-branch: master
        local-dir: docs/.vuepress/dist
        on:
          branch: release/docs

    - stage: deploy to pypi
      if: tag IS present
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
